name: Sync develop with master

on:
  push:
    branches:
      - master  # Aciona o workflow quando há um push na branch master

jobs:
  sync-develop:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que todas as branches sejam buscadas

      # Passo 2: Configurar o Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Passo 3: Fazer o merge da master na develop
      - name: Merge master into develop
        run: |
          git fetch origin
          git checkout develop
          git merge origin/master --no-edit
          git push origin develop
