name: Update branches with master

on:
  push:
    branches:
      - master

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}  # Usa o PAT com permissões de escrita

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get all branches
        id: get-branches
        run: |
          git fetch --all
          BRANCHES=$(git branch -r | grep -v 'origin/master' | sed 's/origin\///')
          echo "branches=$BRANCHES" >> $GITHUB_OUTPUT

      - name: Merge master into all branches
        run: |
          for branch in ${{ steps.get-branches.outputs.branches }}; do
            git checkout $branch
            git pull origin $branch
            git merge origin/master --no-edit
            git push origin $branch
          done
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}  # Usa o PAT para fazer push
